language: python
python:
    - "2.7"
    - "pypy"

install:
    - pip install -r requirements.txt
    - pip install coveralls

script: coverage run --source="." `which trial` eots
after_success: coveralls

